# Generated by Django 6.0 on 2026-01-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Например: Оплата подтверждена / Не совпала сумма', verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='Скриншот оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('in_progress', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён'), ('awaiting_payment', 'Ожидает оплату'), ('awaiting_check', 'Ожидает проверки'), ('rejected', 'Отклонён')], default='new', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать в подборке'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='is_hero',
            field=models.BooleanField(default=False, verbose_name='Показывать в hero-блоке'),
        ),
    ]
