# Generated by Django 6.0 on 2026-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_order_admin_comment_order_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Ожидает оплаты'), ('new', 'Оплачен (на проверке)'), ('accepted', 'Оплата подтверждена'), ('in_progress', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='awaiting_payment', max_length=30, verbose_name='Статус'),
        ),
    ]
